### ISSUE TITLE
ユーザー情報が変更できない

### ISSUE THREAD

**Issue by nsmr0604** [project-primera/ongeki-score#339]
利用規約より
>ユーザーは自己の責任において、本サービスのユーザーIDおよびパスワードを管理するものとします。

とあるが、自己管理を行うにしてもユーザー名の変更や削除、登録メールアドレスの変更が一切できないのは不便である。ユーザー名やメールアドレスを変更したいと思ったら毎回新規登録することになるので手間だしデータベースレコードも増えるのでお互いにメリットが無い。

**Comment by Slime-hatena** [comment]
ありがとうございます。こちらに気づかずTwitterの方のみ返信を差し上げる形となってしまいました。
そちらで言及させていただきましたが、開発者という立場でこちらでも説明させていただきます。

## メールアドレスの変更機能

> ユーザー名の変更や削除、登録メールアドレスの変更が一切できないのは不便である。

メールアドレスの変更機能に関しましては直近での追加の予定はありません。
原因として、現状利用しているLaravel Authでは機能が提供されていないという点があります。
もちろん独自に実装すれば可能ではありますが、ユーザーの認証情報などを扱うと言う観点から、できるだけ独自実装は避けたいという思いがあります。

今後認証をすべてfirebase authに移行するという計画がありますので、その際に実装を行う予定です。

## ユーザー名の変更

> ユーザー名やメールアドレスを変更したいと思ったら毎回新規登録することになるので手間

こちらに関しましては現状表示する箇所が、自身のみという観点から、変更機能の必要性を感じておりません。
こちらも今後プロフィールページに表記する機能を追加時、同時に追加させて頂く予定でございます。

すぐに必要という場合には、お問い合わせでのサポート対応という形で対応させていただいております。

## 個人データの削除について

> ユーザー名の変更、ユーザーの削除及びメールアドレスの変更機能が欲しい。メアドやプレイヤー名が変わるごとに新規登録するのは手間かつデータベースレコードが増えるだけ。何よりユーザー自身が自身の情報を消せないのは不便。
> https://twitter.com/ongeki_score/status/1361331496775086084

こちらのissueには記載がなかったのですが、こちらにも触れさせていただきます。

削除機能に関しては、論理削除の仕組みがないためすぐには難しい状態となります。
物理削除をしてしまうと、いたずらなどの行為に対して対処が難しいためです。
今後データベース構造を変えなくてはならないアップデートがございますため、その際に実装を進めたいと考えております。

また、こちらもお問い合わせによるサポート対応は受け付けております。

## データベースレコードについて

> データベースレコードも増えるのでお互いにメリットが無い

こちらに関しては大したデータ量にならないため、問題には思っておりません。
ユーザーが楽曲データを更新した際のデータのほうが数倍大きいため、レコード構造に関しては変更の予定はございません。

**Comment by Slime-hatena** [comment]
変更点について各issue分解させていただきました。
こちらはcloseさせていただきます。
