### ISSUE TITLE
連携せずに画像化出来るようにして欲しい

### ISSUE THREAD

**Issue by nr1a** [project-primera/ongeki-score#762]
### 関連ページ・機能
更新差分を画像化するためにTwitterの連携をしていないと出来ない仕様のため、TwitterAPIが死んでいると画像化が出来ない。

### リクエストする機能
画像化するだけなら連携は不要だと思っています。
![image](https://github.com/project-primera/ongeki-score/assets/82102170/029442b2-483a-4557-8a32-d123527d21d9)

**Comment by slime-hatena** [comment]
ありがとうございます。（放置してしまい申し訳ございません）
Twitter連携に関してはいろいろと掛け合いましたが、もはやX運営は信用に値しないのでなにかしら行います。

**Comment by slime-hatena** [comment]
かなりチープですが画像化して表示するように変更しました。
問題なければAct3のアップデートから反映される予定です。
