### ISSUE TITLE
アカウント削除機能

### ISSUE THREAD

**Issue by yuu-electrum** [project-primera/ongeki-score#871]
### 関連ページ・機能

アカウントを削除できる機能のご検討をよろしくお願いいたします。

### リクエストする機能

一度アカウントを登録したら削除できないというのは情報保護の観点から問題であると考えておりますので、ご検討のほどよろしくお願いいたします。

**Comment by slime-hatena** [comment]
こんにちは、こちらの内容と重複しているためクローズさせていただきます。
実装自体は難しくコストも高いため現在は見送っております。

ongeki-score.netにおきましてはお問い合わせベースでの削除対応を行っておりますので、必要がありましたら https://x.com/ongeki_score へお問い合わせいただけますと幸いです。

**Comment by slime-hatena** [comment]
ref: #344
